theme: jekyll-theme-cayman
title: Nature-Inspired Intelligence at the service of Nature-Inspired Intelligence
subtitle: Special Session in CEC2021

# header image for the site
header: images/banner_NIA2NIA_draft.png
