theme: jekyll-theme-cayman
title: Nature-Inspired Intelligence at the service of Nature-Inspired Intelligence
subtitle: Special Session on CEC2021

# header image for the site
banner: https://raw.githubusercontent.com/firefly-cpp/NIA2NIA-CEC21/main/banner_NIA2NIA_draft.png

# footer image
footer: https://raw.githubusercontent.com/firefly-cpp/NIA2NIA-CEC21/main/IEEE_CEC_2021_logo_full_23.jpg

navigation:

  - title: Home
    url:
  - title: Important dates
    url: important-dates
  - title: About
    url: about